### PR TITLE
Add vsgrendertotexture example

### PR DESCRIPTION
**Pull request by timoore**
A possible approach to offscreen framebuffers. This won't compile without the changes to VSG in vsg-dev/VulkanSceneGraph#171.

### CODE REVIEW

**Comment by robertosfield** [comment]
@timoore I have been looking to create a VSG example that does multi-pass in a way that is compatible with creating multiple CommandGraph's, the vsgrendertexture is a possible candidate.  Still haven't figured out the details of how to do it yet though... will probably have to come back to that tomorrow.

The reason for this comment is that while reviewing the example I saw the local  SimpleDescriptorImage class, when I looked at the implementation it occurred to me that it overlaps significantly with the vsg::DescriptorImageView.  This class is something that is used in the vsgraytracing example.  I have tried replacing the use of SimpleDescriptorImage with DescriptorImageView and it still works for me.   Did you know about DescriptorImageView? 

The code change was simply:

#if 0
    auto texture = SimpleDescriptorImage::create(colorImage, 0, 0, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER);
#else
    auto texture = vsg::DescriptorImageView::create(colorImage, 0, 0, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER);
#endif

The only difference looks to be the barrier that the DescriptorImageView uses, so I'm thinking that this particular part should probably be moved out of DescriptorImageView.

**Comment by timoore** [comment]
I too discovered DescriptorImageView after submitting the render-to-texture
example and in my local tree have done what you did. DescriptorImageView is
exactly what is needed. I think the barrier is at worst harmless.

My purpose with vsgrendertotexture was to start on the path of sharing
images rendered in VSG with other consumers, in particular OpenVR and
OpenGL / OSG via external objects. Don't know if there are some ideas there
for rendering multiple command graphs. One non-ideal way to do VR is to
render the whole scene graph twice, but that could be done in one command
graph with two RenderGraphs.

I was wondering if you had put any thought into multi-threaded recording of
one scene graph for the same RenderGraph?

Right now I'm working on implementing multisampling in vsg::Viewer, and
then in vsgrendertoexture. It's an interesting problem because, I believe,
you need to traverse the scene graph to add the multisampling state
commands in the appropriate places. Not like in OSG...

**Comment by robertosfield** [comment]
Thanks for the clarification on DescriptorImageView usage.  I will review the barrier in it.  I will need to work through the vsgraytracing example and chat with Tom about the barrier used.  I think that should be done else where, but don't know enough at this point to know exactly what should be done where.  For now I'm happy to just leave the local implementation in place, as I have other issues to wrap up first.

On the interoperability side Tom did some work on OpenGL/OSG/VSG integration in the osg2vsg project.  There a GLinterop branch there.  I never got it working under Linux and haven't had time to get things working.  I'd start there with you own investigation into it.  I'd like to make this type of functionality available to all that need it.  It has to work across platforms first though.  I'd be happy for others to pick up the baton on this one.

W.r.t multi-threading of RenderGraph, Vulkan itself is designed around separate threads creating separate command buffers, if you place mulitple render passes within single command buffer then you have to do the recording within a single threaded.  

The VSG wraps up the render pass recording within a RenderGrah, and the command buffer recording within a CommandGraph.  A single CommandGraph can have zero, 1 or many RenderGraph(render passes).  In Vulkan can place separate render passes into separate command buffers and record them separately, so in the VSG this maps to having multiple CommandGraph each one having a single RenderGraph.

In your original vsgrendertexture example you placed two RenderGraph(render passes) within a single CommandGraph and this works fine but precludes threading of the recording.  To enable threading of recording we need multiple CommandGraph so the solution is to use two CommandGraph, then the VSG can use a separate thread for each CommandGraph/RenderGraph combination.  

This is what I'm experimenting right now.  I have modified your example to optional use threading and optional use multiple command graph.  I have single threaded multiple command graph work with your example.  Multi-threaded command graph isn't working yet though  currently hangs.

W.r.t multi-sampling, it's not something I've tried yet, so it'll be interesting to see what you come up with.  As you say some aspects of Vulkan and also the VSG have state more tightly coupled with the scene graph than OSG/OpenGL combo.  OpenGL does lots of work for us hiding us from the complexity of some of the coupling that happens down on the GPU, Vulkan forces us to explicitly link everything required together into a pipeline state.  

Changing that pipeline state requires us to dig into the scene graph's state set to local all the GraphicsPipeline and the states it manages and replace them with a new GraphicsPipeline and new state. 

If you are building all the state manually you can add in the specific state you are interested in and won't need to go hunting things down later.  This doesn't quite fit with how most graphics applications work though, data, scene state and window state are all pretty decoupled.

For the VSG it's a case of working out how to encapsulate Vulkan in appropriate way, then working out ways to provide conveniently ways of managing it at the application level.  Some of this might be done at the scene graph class level, others might convenience functions that help do standard operations, or provide standard configurations that make life easier.

**Comment by timoore** [comment]
On Wed, May 13, 2020 at 1:16 PM Robert Osfield <notifications@github.com>
wrote:

>
> W.r.t multi-threading of RenderGraph, Vulkan itself is designed around
> separate threads creating separate command buffers, if you place mulitple
> render passes within single command buffer then you have to do the
> recording within a single threaded.
>
> The VSG wraps up the render pass recording within a RenderGrah, and the
> command buffer recording within a CommandGraph. A single CommandGraph can
> have zero, 1 or many RenderGraph(render passes). In Vulkan can place
> separate render passes into separate command buffers and record them
> separately, so in the VSG this maps to having multiple CommandGraph each
> one having a single RenderGraph.
>
> In your original vsgrendertexture example you placed two
> RenderGraph(render passes) within a single CommandGraph and this works fine
> but precludes threading of the recording. To enable threading of recording
> we need multiple CommandGraph so the solution is to use two CommandGraph,
> then the VSG can use a separate thread for each CommandGraph/RenderGraph
> combination.
>
Actually, I was thinking of secondary command buffers, which aren't
required to contain a RenderPass. If you record to secondary command
buffers, then on dispatch you only need a single render pass and command
buffer.

> This is what I'm experimenting right now. I have modified your example to
> optional use threading and optional use multiple command graph. I have
> single threaded multiple command graph work with your example.
> Multi-threaded command graph isn't working yet though currently hangs.
>
Cool, I'm glad it is useful.

>
>

**Comment by robertosfield** [comment]
Secondary command buffers isn't something I've personally tackled yet, it's on my TODO list to properly review and resolve the best way forward.  The subpass work by @juval has spearheaded support for secondary command buffers, part of this work is already part of master.

I have got some many bridges to cross on the VSG I'm having to take things bit by bit to avoid sinking into a quagmire of confusion.  My work plan has been to flesh out the multi-threading functionality and get it merged this week then look at secondary command buffers after this.

If you want to dive in with an alternate implementation that uses secondary command buffers with the vsgrendertexture example then go for it.

One of the variations for vsgrendertexture that might be interesting would be a cube map version, probably deserves a whole new example for that though.  It would provide an example of using 6 renderings of texture faces and use of this in the main rendering.  Should be possible manage that all with 7 CommandGraph, one for each face and one for the main scene graph.  

Doing shadows would be another interesting example... 

One thing at time though.  Have to get the multi-threaded side working for vsgrendertexture first!

**Pull request merged**
