### PR TITLE
Add custom fonts to vsgimgui example

### PR DESCRIPTION
**Pull request by rolandhill**
Optionally add a custom font to your ImGui components by setting #define CUSTOMFONTS to 0 or 1. You will see that the font used in the example dialog changes.

Note that this PR hard wires the location of the calibri font file in line 91 and should be changed to something more general.

This assumes that vsgImGui PR #20 has been implemented to prevent RenderImGui calling _uploadFonts() in its constructor.

### CODE REVIEW

**Comment by robertosfield** [comment]
I have merged the changes to rolandhill-CustomFont branch for testing purposes.  I may create a new example from this.

**Comment by robertosfield** [comment]
This PR refers to a font file that 

$ vsgimgui 
Failed to load font: ../../data/fonts/calibri.ttf

I can get it to work if I run vsgimui from vsgExamples/examples/ui/.  I'm thinking this modified example should search for the font using the standard vsg::findFile() method.  Thoughts?

**Comment by rolandhill** [comment]
Agreed. I noted that it was hardwired and would need to be modified to be
more robust. I don't use findFile and it didn't come to mind when I did the
example.

**Comment by robertosfield** [comment]
Hi Roland,

I been trying to glean what needs to happen when with the ImGui setup and
believe I've figured out how to get the vsgimgui code with the custom font
to work with the existing vsgImGui without any further modifications, the
following #if 0 code block in your original code path that requires the
modified vsgImGui and the #else block is my experimental code block when I
call ImGui::CreateContext() and then initialize the font before calling
RenderimGui:::create():

#if 0
        auto gui = vsgImGui::RenderImGui::create(window, false, false);
        gui->add(*guiComponent);

        guiComponent->initFonts();
        gui->_uploadFonts();
#else
        ImGui::CreateContext();
        guiComponent->initFonts();
        auto gui = vsgImGui::RenderImGui::create(window);
        gui->add(*guiComponent);
#endif

I'm still not 100% taken with the later approach but I thought I'd throw it
out there as work in progress that might help inform discussions,

Thoughts?
Robert.

**Comment by robertosfield** [comment]
What I have gone for is a modification of the vsgimgui example to allow you to set the font file without any modifications to vsgImGui itself.  The PR is #164.

Usage is:

        if (fontFile)
        {
            auto foundFontFile = vsg::findFile(fontFile, options);
            if (foundFontFile)
            {
                // convert native filename to UTF8 string that is compatible with ImuGUi.
                std::string c_fontFile = foundFontFile.string();

                // initiaze ImGui
                ImGui::CreateContext();

                // read the font via ImGui, which will then be current when vsgImGui::RenderImGui initializes the rest of ImGui/Vulkan below
                ImGuiIO& io = ImGui::GetIO();
                auto imguiFont = io.Fonts->AddFontFromFileTTF(c_fontFile.c_str(), fontSize);
                if (!imguiFont)
                {
                    std::cout << "Failed to load font: " << c_fontFile << std::endl;
                    return 0;
                }
            }
        }

**Pull request closed without merging**
