### PR TITLE
add multipass example

### PR DESCRIPTION
**Pull request by mp3butcher**

### CODE REVIEW

**Comment by vsg-dev** [comment]
I have merged and tested the vsgsubpass example and it opens a window then just hangs are reports:

RecordAndSubmitTask::submit(ref_ptr<FrameStamp> frameStamp)) fence->wait(10000000000) failed with result = 2
RecordAndSubmitTask::submit(ref_ptr<FrameStamp> frameStamp)) fence->wait(10000000000) failed with result = 2
RecordAndSubmitTask::submit(ref_ptr<FrameStamp> frameStamp)) fence->wait(10000000000) failed with result = 2

I haven't looked into what is going on yet. Is this working OK for you?

Could you provide a screenshot of what I should expect?

**Comment by vsg-dev** [comment]
I've run vsgsubpass -d to use the Vulkan debug layer, this is what I get:

VUID-VkSubpassDescription-pPreserveAttachments-00854(ERROR / SPEC): msgNum: 0 - vkCreateRenderPass(): subpass 0 uses attachment 0 as both depth and color attachment. The Vulkan spec states: Each element of pPreserveAttachments must not also be an element of any other member of the subpass description (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkSubpassDescription-pPreserveAttachments-00854)
    Objects: 1
        [0] 0, type: 0, name: NULL
VUID-VkSubpassDependency-srcAccessMask-00868(ERROR / SPEC): msgNum: 0 - ValidateCreateRenderPass(): pDependencies[0].srcAccessMask (0x400) is not supported by srcStageMask (0x400). The Vulkan spec states: Any access flag included in srcAccessMask must be supported by one of the pipeline stages in srcStageMask, as specified in the table of supported access types (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkSubpassDependency-srcAccessMask-00868)
    Objects: 1
        [0] 0, type: 0, name: NULL
VUID-VkSubpassDependency-dstAccessMask-00869(ERROR / SPEC): msgNum: 0 - ValidateCreateRenderPass(): pDependencies[0].dstAccessMask (0xa0) is not supported by dstStageMask (0x400). The Vulkan spec states: Any access flag included in dstAccessMask must be supported by one of the pipeline stages in dstStageMask, as specified in the table of supported access types (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkSubpassDependency-dstAccessMask-00869)
    Objects: 1
        [0] 0, type: 0, name: NULL
VUID-VkAttachmentReference-layout-00857(ERROR / SPEC): msgNum: 0 - Layout for depth attachment reference in subpass 0 is VK_IMAGE_LAYOUT_UNDEFINED but must be a valid depth/stencil layout or GENERAL. The Vulkan spec states: If attachment is not VK_ATTACHMENT_UNUSED, layout must not be VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_PREINITIALIZED, VK_IMAGE_LAYOUT_PRESENT_SRC_KHR, VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL_KHR, VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL_KHR, VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL_KHR, or VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL_KHR (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkAttachmentReference-layout-00857)
    Objects: 1
        [0] 0, type: 0, name: NULL
VUID-VkFramebufferCreateInfo-pAttachments-02633(ERROR / SPEC): msgNum: 0 - vkCreateFramebuffer:  Framebuffer Attachment (0) conflicts with the image's IMAGE_USAGE flags (VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT). The Vulkan spec states: If flags does not include VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of pAttachments that is used as a depth/stencil attachment by renderPass must have been created with a usage value including VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkFramebufferCreateInfo-pAttachments-02633)
    Objects: 1
        [0] 0, type: 0, name: NULL
VUID-VkFramebufferCreateInfo-pAttachments-02633(ERROR / SPEC): msgNum: 0 - vkCreateFramebuffer:  Framebuffer Attachment (0) conflicts with the image's IMAGE_USAGE flags (VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT). The Vulkan spec states: If flags does not include VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of pAttachments that is used as a depth/stencil attachment by renderPass must have been created with a usage value including VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkFramebufferCreateInfo-pAttachments-02633)
    Objects: 1
        [0] 0, type: 0, name: NULL
VUID-VkFramebufferCreateInfo-pAttachments-02633(ERROR / SPEC): msgNum: 0 - vkCreateFramebuffer:  Framebuffer Attachment (0) conflicts with the image's IMAGE_USAGE flags (VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT). The Vulkan spec states: If flags does not include VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of pAttachments that is used as a depth/stencil attachment by renderPass must have been created with a usage value including VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkFramebufferCreateInfo-pAttachments-02633)
    Objects: 1
        [0] 0, type: 0, name: NULL
UNASSIGNED-CoreValidation-DrawState-InvalidRenderpass(ERROR / SPEC): msgNum: 0 - Cannot use same attachment (0) as both color and depth output in same subpass (0).
    Objects: 1
        [0] 0, type: 0, name: NULL
VUID-vkCmdDrawIndexed-subpass-02685(ERROR / SPEC): msgNum: 0 - Pipeline was built for subpass 0 but used in subpass 1. The Vulkan spec states: The subpass index of the current render pass must be equal to the subpass member of the VkGraphicsPipelineCreateInfo structure specified when creating the VkPipeline bound to VK_PIPELINE_BIND_POINT_GRAPHICS. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdDrawIndexed-subpass-02685)
    Objects: 1
        [0] 0x210000000021, type: 19, name: NULL
UNASSIGNED-CoreValidation-DrawState-InvalidRenderpass(ERROR / SPEC): msgNum: 0 - Cannot use same attachment (0) as both color and depth output in same subpass (0).
    Objects: 1
        [0] 0, type: 0, name: NULL
VUID-vkCmdDrawIndexed-subpass-02685(ERROR / SPEC): msgNum: 0 - Pipeline was built for subpass 0 but used in subpass 1. The Vulkan spec states: The subpass index of the current render pass must be equal to the subpass member of the VkGraphicsPipelineCreateInfo structure specified when creating the VkPipeline bound to VK_PIPELINE_BIND_POINT_GRAPHICS. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdDrawIndexed-subpass-02685)
    Objects: 1
        [0] 0x210000000021, type: 19, name: NULL
UNASSIGNED-CoreValidation-DrawState-InvalidRenderpass(ERROR / SPEC): msgNum: 0 - Cannot use same attachment (0) as both color and depth output in same subpass (0).
    Objects: 1
        [0] 0, type: 0, name: NULL
VUID-vkCmdDrawIndexed-subpass-02685(ERROR / SPEC): msgNum: 0 - Pipeline was built for subpass 0 but used in subpass 1. The Vulkan spec states: The subpass index of the current render pass must be equal to the subpass member of the VkGraphicsPipelineCreateInfo structure specified when creating the VkPipeline bound to VK_PIPELINE_BIND_POINT_GRAPHICS. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdDrawIndexed-subpass-02685)
    Objects: 1
        [0] 0x210000000021, type: 19, name: NULL
^C

**Comment by mp3butcher** [comment]
damned....it seems MESA is more permissive for vulkan than for opengl....

**Comment by vsg-dev** [comment]
Does mesa have the debug layer? The debug and api layers are invaluable at catching problems.

**Comment by mp3butcher** [comment]
it's just that without -d i don't have layer messages (haven't isntalled
it)...
and as it gives good graphics results i though it was enough
I just install lunar vk and have same behavior as you now

Le mar. 4 févr. 2020 à 09:54, Vulkan made easy <notifications@github.com> a
écrit :

**Pull request merged**
