### PR TITLE
Annotation with debug_utils example

### PR DESCRIPTION
**Pull request by timoore**
This example shows how to insert nodes in the scene graph with annotations that can be used by debugging programs like RenderDoc. A screenshot of the RenderDoc display is included.

### CODE REVIEW

**Comment by robertosfield** [comment]
I have merged as a timoore-annotation branch:

https://github.com/vsg-dev/vsgExamples/tree/timoore-annotation

I'll now get things compiling and have a bash at use RenderDoc with it.  I did wonder about naming the example vsgrendrdoc if it's mainly about enabling high quality RenderDoc usage.

**Comment by robertosfield** [comment]
I have got it working with qrenderdoc, found out that ~ doesn't work for paths in RenderDoc which lots me few minutes trying to figure out why things weren't starting up...

I can see the annotation, it's a bit limited though, so I'm thinking that it might be nice to have a visitor that goes through the scene graph and insert annotation nodes.  Can this extension handle nesting?

I am also thinking about whether we need the EXT at the end of the function names.  I presume at some point Vulkan will move these from EXT.

**Comment by robertosfield** [comment]
@timoore I am curious why you added the following definitions as I don't think they are necessary, and if they are the a using should be sufficient to make sure they are still available.  Just commenting them out things still work fine for me. 

~~~ cpp
#if 0
        // ParentClass::accept() is hidden by overriding accept(RecordTraversal&), so we need to
        // reimplement the other variations too in order to be able to call them directly.
        void accept(vsg::Visitor& visitor) override
        {
            ParentClass::accept(visitor);
        }

        void accept(vsg::ConstVisitor& visitor) const override
        {
            ParentClass::accept(visitor);
        }
#endif
~~~

**Comment by timoore** [comment]
> If I'm reading this correct it looks like this extension is part of Vulkan 1.3:
> 
> https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_tooling_info.html

The tooling info extension has been promoted, but  I don't think that debug_utils has been.

**Comment by robertosfield** [comment]
On the tooling info page I says "Interacts with VK_EXT_debug_utils == Deprecation State" which makes me wonder if the VK_EXT_debug_utils is being subsumed into something else.

**Comment by robertosfield** [comment]
Reviewing the code, I find the line:

~~~ cpp
std::copy(&debugColor.value[0], &debugColor.value[4], &markerInfo.color[0]);
~~~

rather more cryptic than I'd like.  I have tried a couple variations of help functions but not come up with anything that I'm happy with yet.  Perhaps a helper function in include/vsg/maths/color,h?  A copy member function of vsg::vec4?  

I'm open to suggestions about what might be more expressive than a std::copy() that you have closely read to know for sure it's doing something intended.

This needn't hold up merging this branch though.

**Comment by robertosfield** [comment]
Forgot to mention, if we want to annotate stuff that goes into the transpent bin then subclassing from vsg::Bin and then assigning this to the View at the appropriate slot would be the way to do it.

**Pull request merged**
