### PR TITLE
vsgExamples Issues#196

### PR DESCRIPTION
**Pull request by bizehao**
vsgmultiviews example in vsgmultiviewsForIssues196

### CODE REVIEW

**Comment by robertosfield** [comment]
Thanks,  I have merged as a bizehao-master branch:

https://github.com/vsg-dev/vsgExamples/tree/bizehao-master

I get lots of compile warnings here on Linux but it looks run OK when I use:

`vsgmultiviewsForIssues196 models/lz.vsgt -s`

I see a serious flicker when I run without -s though.  When I run without -s and with -d I see lots of these Vulkan debug errors:

       [0] 0x55a7e841f5a0, type: 4, name: NULL
VUID-VkPresentInfoKHR-pImageIndices-01296(ERROR / SPEC): msgNum: -945112042 - Validation Error: [ VUID-VkPresentInfoKHR-pImageIndices-01296 ] Object 0: handle = 0x55a7e841f5a0, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xc7aabc16 | vkQueuePresentKHR(): pSwapchains[0] images passed to present must be in layout VK_IMAGE_LAYOUT_PRESENT_SRC_KHR or VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR but is in VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL. The Vulkan spec states: Each element of pImageIndices must be the index of a presentable image acquired from the swapchain specified by the corresponding element of the pSwapchains array, and the presented image subresource must be in the VK_IMAGE_LAYOUT_PRESENT_SRC_KHR layout at the time the operation is executed on a VkDevice (https://github.com/KhronosGroup/Vulkan-Docs/search?q=)VUID-VkPresentInfoKHR-pImageIndices-01296)

--

I will now do a review of the changes compared to the original vsgmultiviews example and see what I can learn about it.

@bizehao Does this PR resolve the visual problems for you when running with -s? What happens without -s?

**Comment by robertosfield** [comment]
@bizehao I'm reviewing the changes and have a few queries.

What was the motivation for the CustomImageMemoryBarrierCmd rather than using the [vsg::PipelineBarrier](https://github.com/vsg-dev/VulkanSceneGraph/blob/master/include/vsg/commands/PipelineBarrier.h) + vsg::ImageMemoryBarrier?

What happens when you don't have the barriers? 

I am wondering if a RenderPass subpass might appropriate to use as this should offer another way of synchronizing things, thought I have a vague recollection of wondering about mutiple subpasses for multview when I first implemented vsgmultiviews but as this was a few years back I don't recall why I didn't implement a path this way, it might not be possible.  I will have a look at the vsgsubpass example and see if that might be helpful.  subpasses should handle the synchronization so the pipeline barrier shouldn't be required.

When reviewing the Anvil code did you glean why it works while the original vsgmultiviews example fails on your system? Does it look to be a synchronization issue?

**Comment by bizehao** [comment]
Sorry, I was careless, I didn't test without -s, I just made some changes, and pushed it to https://github.com/vsg-dev/vsgExamples/tree/bizehao-master

**Comment by bizehao** [comment]
Yes, it solves the -s problem, because using the vsg::P ipelineBarrier + vsg::ImageMemoryBarrier, it needs image, I can't get the image of the corresponding index outside. No correlation was found in the example

**Comment by bizehao** [comment]
I looked at the Anvil code, and I found that the problem was on vsg::AttachmentDescription.initialLayout, so I referred to the Anvil's multiviews code, made this change, and it was normal

**Comment by robertosfield** [comment]
Thanks for the explanation.

I have created a vsgmultiview_subpass branch to experiment with use a RenderPass with multiple subpasses:

https://github.com/vsg-dev/vsgExamples/tree/vsgmultiview_subpass

The subpass does the synchronization for us, so shouldn't need any extra synchronization primitives.  The current implementation doesn't clear the colour buffer so we see the insert view overlay on the main view.  Could you try this branch and then run:

```
vsgmultiviews models/lz.vsgt --ca
Using a single RenderGraph, with both Views separated by a ClearAttachments

$ vsgmultiviews models/lz.vsgt --rg
Using a RenderGraph per View

$ vsgmultiviews models/lz.vsgt --sp
Using RenderPass Subpasses

```

As the --rg RenderGraph one is unchanged from the original vsgmultiviews I would still expect this to fail on your system.

I will now try to enable the clear background color for the subpass approach.  

It may be that the if the separate RenderGraph approach requires lots extra complexity w.r.t synchronization to get it work on all systems then it might be an approach we simply remove from vsgmultiviews.

**Comment by robertosfield** [comment]
I have investigated the controls we have available for subpasses and the only way I can find for the second view/subpass to have a clear of colour and depth buffer is to do explicitly with clear attachments.  Considering you also need to set up a custom RenderPass for this usage case it's more complicated.

Essentially a RenderPass with mutliple subpasses is really ideal for rendering that layers rendering passes, rather than for multiple view usage case where each view is independent, save for render order.

**Comment by robertosfield** [comment]
I've fixed the problem with running vsgmultiviewsForIssues196 without -s: 8181c8d7864d4e2f73d634a0142cf4f97a428b7d

I am now back reviewing your changes.

**Comment by robertosfield** [comment]
Looking at the custom pipeline barrier code, I think the vsg::PipelineBarrier/ImageBarrier is sufficient, all you need to do is assign the appropriate image prior to the viewer.recordAndSubmit() call.

**Comment by robertosfield** [comment]
I don't understand the role of the beginBarrier and endBarrier, as the RenderPass/Swapchain itself should avoid the previous frame being overwritten by the new frame being rendering.

If the barriers were required we'd see issues on all types of rendering, not just this special case of having two RenderGraph/RenderPass.  

What happens if you remove the begin barrier, the end barrier or both the begin and end barrier?

I am now wondering if your driver is getting confused by having two RenderPass within a single CommandGraph and if releasing the RecordAndSubmit's signalSemaphores that is present waits for.

This just makes me think that it's a driver bug and these extra barriers are just hiding it.

**Comment by robertosfield** [comment]
I have just done a comparison of the API output of vsgmultiviews vs vsgmultiviewsForIssues196 and see a key difference is the vsgmultiviews has the two RenderGraph/RenderPass having 

    colorAttachment.finalLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR; 
vs
    colorAttachment.finalLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL

Which I guess explains the need for the barriers that aren't normally needed.

Perhaps the driver is responding the the attachment layout going to VK_IMAGE_LAYOUT_PRESENT_SRC_KHR after the rendering of the first RenderGraph and just going ahead copying to the swap chain image, even thought there is still work being carried out, and then copy and the rendering are occurring at the same time.

Um.... done more thinking and reviewing of the two API outputs and am still not clear exactly what might be going on, but might be getting a bit closer.  I'll do some more thinking and tinkering in the direction of tweaking the settings of the two RenderGraph/RenderPass so that first one doesn't set the finalLayout to PRESENT_SRC, leaving this to the second RenderGraph.

**Comment by robertosfield** [comment]
I've done more reflecting on the issue how to get multiple RenderGraph that share the same window to play nice and have come to the conclusion that the approach you've taken is broadly workable, but if it takes so much extra code and complexity to workaround the intended design of vkRenderPass/vkFramebuffer that it's a clear indicator that it's just the wrong approach.

Rather than attempt to clean up the workarounds you've come up with I think best way forward is to simplify vsgmultiviews so it just has the clear attachments implementation and to remove the RenderGraph per View approach completely.  My brief experiment with subpasses offered nothing over just using clear attachments directly so I will abandon that experiment as well.

Apologies for taking so long to come to this conclusion, this part of Vulkan is a bit awkward and reveals is roots as an API for modern games on modern graphics hardware that has been generalized enough to handle more general purpose graphics applications,

Thanks for your efforts trying to get to the bottom of the multi RenderGraph issues, I've learned/clarified a few things about Vulkan and Vulkan drivers/hardware because of this.

**Pull request closed without merging**
