### PR TITLE
Stats event handler for vsgviewer

### PR DESCRIPTION
**Pull request by rhabacker**
With this commit, event handlers with a graphical interface are now possible.

### CODE REVIEW

**Comment by robertosfield** [comment]
Very cool addition.  Adding a  vsgImGui dependency to vsgviewer is not ideal though as it's not a standard dependency.  This might be better made as a dedicated example separate from vsgviewer or made an optional compile.

Another route would be to implement the same functionality using native VSG classes that way it could remain part of vsgviewer.

**Comment by rhabacker** [comment]
> Very cool addition.

This is one of the missing feature of vsgviewer compared to the osgviewer. osgviewer here is the basic tool for viewing and checking/debugging models and scenes, generating screenshots. For vsgviewer to be used to the same extent, a few things were missing.

>  This might be better made as a dedicated example separate from vsgviewer 

There is already an example of using vsgImGui, but I think vsgviewer is more than just an example, as described above.

> made an optional compile.

This has been implemented with https://github.com/vsg-dev/vsgExamples/pull/195/commits/a4470d8f558352d0eb1148d969d153a542f07f6c.

> Another route would be to implement the same functionality using native VSG classes that way it could remain part of vsgviewer.

This sounds good in any case, but requires some analysis and design work to obtain suitable functions.

Decisive questions here are, in my opinion, whether one can adopt the design available in osg, whether Vulkan/VSG already offers better possibilities here and how one sets this up in principle, e.g. whether one provides a separate scene graph, camera and view for each handler and attaches the latter to the render graph, or whether there are other/better ways. Then there is the question of how to switch the visual objects of the handlers on and off at runtime.

**Comment by robertosfield** [comment]
This is an interesting test for vsgImGui and the VSG, as well as useful features for vsgviewer. so I'm pleased to see it evolve.

I'm busy with client work today so can't dive into it yet, but tomorrow I will test put some time aside to test and play with it.

**Comment by rhabacker** [comment]
>This is an interesting test for vsgImGui and VSG, 

Yes and I have already found two things: 

1. after pressing 's' or 'h', when moving the related vsgImGui based window, the change also affects the scene.
2. the key mapping between vsg and vsgimGui is incomplete, it was necessary to add additional entries.

> as well as useful functions for vsgviewer. So I'm glad that this has evolved.

Yes, for example if you start vsgviewer with `--IMMEADIATE` and press 's' you can see directly the actual speed at which vsg renders.

**Comment by robertosfield** [comment]
@rhabacker I have created a branch for this work:

     [rhabacker-StatsEventHandler](https://github.com/vsg-dev/vsgExamples/tree/rhabacker-StatsEventHandler)

I have compiled it and the help and stats work fine for me.  I am now doing a general review and refactor of what is defined where.  

Why did you create a local CloseHandler when the VSG has one itself?

**Comment by robertosfield** [comment]
I have figured out the reason for the local CloseHandler - a way to inject the keyboard mapping to the HelpHandler. However, this type of object integration via static doesn't feel like good solution to this particular problem.

At this point the PR is not suitable for integration with vsgExamples master. I will need to spend more time with the code to know how it should evolve to get it to place where it's suitable example of how to do this type of functionality.  We need to get it right because vsgviewer will likely server as a common source of inspiration as folks started writing their own VSG based applications.

**Comment by robertosfield** [comment]
I'm going to close this PR, as I think it's best that future work in this direction and done against the [rhabacker-StatsEventHandler](https://github.com/vsg-dev/vsgExamples/tree/rhabacker-StatsEventHandler)
 branch.   

As things stand it's not suitable for merging with vsgExamples master especially this close to me making a 1.0.1 maintenance release.

**Pull request closed without merging**
