### PR TITLE
Spotlight shadows

### PR DESCRIPTION
**Pull request by AnyOldName3**
This should be everything that needs to change in this repo to make everything work as well as it does for directional lights.

In fact, the implementation for everything except PCSS is literally identical for spot and directional lights, so could be folded into the same function if that's preferred.

Obviously, this depends on https://github.com/vsg-dev/VulkanSceneGraph/pull/1155

### CODE REVIEW

**Comment by robertosfield** [comment]
Thanks merged as AnyOldName3-spot-shadows.  Will started testing and reviewing.

**Comment by robertosfield** [comment]
What is the best command line option combination to test out the new spot light shadows?

When I run:
~~~ sh
 vsgshadow -n 4 --dc
~~~

This is what I currently get after merging the VSG and vsgExamples spot-shadows PRs:
Screenshot_20240412_184138

This doesn't look like I have shadows for the spot light yet.  Do I need to rebuild shaders?

**Comment by robertosfield** [comment]
I have tweaked vsgshadow to just assign the ambient and spot lights when -n 4 is used, I don't see any shadows yet.  

I ran with --shader-debug enabled:
~~~ sh
vsgshadow -n 4 --dc --shader-debug 
~~~

And this is what I get:
Screenshot_20240412_185345

So this looks like the shadow map is nice and tightly bound to the spot light frustum, just the shadows are missing.

Any ideas?

**Comment by AnyOldName3** [comment]
A mixup between `<` and `>` in the optimisation commit. I've pushed a fix.

**Comment by robertosfield** [comment]
I tried applying that last commit by hand - I haven't merged with vsgExamples master but the AnyOldName3-spot-shadows branch.

~~~ sh
diff --git a/data/shaders/standard_phong.frag b/data/shaders/standard_phong.frag
index 220c98b..769c0f0 100644
--- a/data/shaders/standard_phong.frag
+++ b/data/shaders/standard_phong.frag
@@ -295,7 +295,7 @@ void main()
             int shadowMapCount = int(lightData.values[lightDataIndex].r);
             if (shadowMapCount > 0)
             {
-                if (lightDirection_cosOuterAngle.w > dot_lightdirection)
+                if (lightDirection_cosOuterAngle.w < dot_lightdirection)
                     brightness *= (1.0-calculateShadowCoverageForSpotLight(lightDataIndex, shadowMapIndex, T, B, dist, color));
 
                 lightDataIndex += 1 + 8 * shadowMapCount;
~~~

Even if I delete the line 
~~~ cpp
 if (lightDirection_cosOuterAngle.w < dot_lightdirection)
~~~
To force the check against the shadow map I still don't see any shadows.

**Comment by robertosfield** [comment]
Working on my laptop and I hadn't synced the VSG version with spot-shadows branch, once I updated and testing spot shadows now works :-)

image

**Comment by robertosfield** [comment]
Now merged with VSG/vsgExamples master.

**Pull request closed without merging**
